org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.252
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=splendidpendants
mod_name=Splendid Pendants
mod_license=MIT
mod_version=0.6.0
mod_group_id=dunkmania101.splendidpendants
mod_authors=Dunkmania101
mod_description=Adds some pendants that give the player great strengths. Splendid!

curios_version=9.5.1+1.21.1
curios_version_range=[9.0.0+1.21.1,)
